apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-ssh
  namespace: rundeck
spec:
  storageClassName:	nfs-tier1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-data
  namespace: rundeck
spec:
  storageClassName:	nfs-tier1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-rundeck-database
  namespace: rundeck
spec:
  storageClassName:	nfs-tier1
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeMode: Filesystem